# Configuration file for baseline models cross-validation
# Supported models: Mean, SVM, LightGBM

dataset:
  data_dir: "./data/processed/eSEEd_v2/"  # Path to processed CSVs
  file_list: null  # null = load all *.csv in data_dir
  window_length: 10  # seconds
  dropping_emotion_threshold: 0  # Drop (subject, recording) pairs where all emotion values are <= this threshold

baselines:
  models:
    - Mean
    - SVM
    - LightGBM
  hyperparameters:
    Mean: {}
    SVM:
      n_jobs: -1
    LightGBM:
      n_jobs: -1
      verbose: -1

cross_validation:
  strategies:
    - "subject_loo"
    - "recording_loo"
   # - "combined_loo"
  val_size: 1
  random_state: 42

logging:
  results_dir: "./results/BaselineCV/eSEEd_v2/"  # Base directory for baseline CV runs

metrics:
  - "mse"
  - "mae"
  - "sd_error"
  - "spearman"
  - "ccc"