data_dir: "data/processed"
seed: 111
experiment_name: "NextPointGNN" 

model:
  name: "NextPointGNN" 
  layer: "GCNConv" # SAGEConv, GATConv, GCNConv, GINConv, TransformerConv
  hidden_dim: 64
  layers: 2
  use_edge_attr: true

data:  
  lookback: 2

train:
  test_set: None # optional name of a dataset to hold out for testing only
  save: true
  save_dir: "checkpoints" # only used if save is true
  
  val_split: 0.2
  batch_size: 8 
  
  lr: 0.001
  epochs: 100
  log_epochs: 10
  early_stopping: true
  patience: 30


